spring:
  application:
    name: eureka-server

logging:
  level:
    org:
      springframework: error
    com:
      netflix:
        discovery: error
    tech: debug
  pattern:
    console: "%clr(%d){blue} [%clr(%-5level){lightgreen}] [%logger{0}] - %msg%n"
    file: "%d [%-5level] [%logger{0}] - %msg%n"
